config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class = "container padded-top">
  <h1>This is my title</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean consequat lorem purus, non facilisis augue suscipit a. Vivamus et dictum felis.
     Pellentesque et nibh sed dolor gravida feugiat congue vitae enim. Phasellus convallis odio nec neque scelerisque tristique. Sed nec luctus nibh.
      Vestibulum neque urna, egestas quis suscipit a, tincidunt eget dui. Aenean efficitur ligula tortor, vel malesuada libero ullamcorper vitae.
      Nulla vitae erat sed lectus pretium pharetra. Praesent sed mauris nibh. Maecenas posuere sapien nec ligula feugiat consequat.
       Praesent malesuada nunc eget ante molestie, aliquet dictum eros ornare.
     Mauris convallis finibus orci eu convallis. Curabitur in libero lacus.</p>

     <!--right panel element -->
     <div class = "col-sm-offset-6 col-sm-6 padded-top">
       <div class = "panel panel-default panel-shadowed">
         <div class = "row">

          <!--Panel content-->
           <div class = "panel-body">
              <h3 class = "padding-left-5">Panel Header</h3>
              <p class = "padding-left-5 padding-right-5 padding-bottom-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean consequat lorem purus, non facilisis augue suscipit a. Vivamus et dictum felis.
                  Pellentesque et nibh sed dolor gravida feugiat congue vitae enim. Phasellus convallis odio nec neque scelerisque tristique. Sed nec luctus nibh.
                   Vestibulum neque urna, egestas quis suscipit a, tincidunt eget dui. Aenean efficitur ligula tortor, vel malesuada libero ullamcorper vitae.
                   Nulla vitae erat sed lectus pretium pharetra. Praesent sed mauris nibh. Maecenas posuere sapien nec ligula feugiat consequat.
                    Praesent malesuada nunc eget ante molestie, aliquet dictum eros ornare.
                  Mauris convallis finibus orci eu convallis. Curabitur in libero lacus.</p>
          </div>
          <!--/panel content -->

          <!-- Button Generic-->
           <div class = "col-sm-offset-4 col-sm-4 padding-bottom-5">
             <div class="actions">
               <button type="submit" class = "btn btn-primary btn-lg btn-block btn-theme"  name="commit"/>Button</button>
             </div>
           </div>
           <!--/button generic-->

         </div>
       </div>
     </div>
     <!--/right panel element -- >

<!--/container -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMM</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li><a href="../navbar-static-top/">Static top</a></li>
            <% if user_signed_in? %>
              <li class = "active">
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
            <% else %>
              <li class = "active">
              <%= link_to('Login', new_user_session_path)  %>
              </li>
            <% end %>
            <!--<li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>



<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>